<a href="https://colab.research.google.com/github/chandru1311/MLOPS-Tasks/blob/main/test%26train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

df = pd.read_csv("civic_issue_dataset.csv")
df.head()

,Report_ID,Date_Submitted,Hour_of_Day,Issue_Type,Department,Zone,Severity_Score,Severity_Label,Num_Upvotes,Has_Photo,Has_Voice_Note,Population_Density,Dept_Current_Workload,Weather_Severity_Index,Priority_Score,Resolution_Time_Hours,Citizen_Satisfaction_Score
0,RPT-01001,2023-01-01,3,Broken Sidewalk,Public Works,Zone E,3,High,9,0,1,772,32,1,19.11,51.6,4.6
1,RPT-01002,2023-01-01,17,Drainage,Public Works,Zone E,4,Critical,17,0,0,1532,52,5,27.67,42.6,2.8
2,RPT-01003,2023-01-02,6,Graffiti,Maintenance,Zone A,1,Low,1,0,1,4953,42,1,19.21,62.1,1.0
3,RPT-01004,2023-01-03,12,Broken Sidewalk,Public Works,Zone C,3,High,7,1,0,4202,35,3,25.50,43.1,6.3
4,RPT-01005,2023-01-03,14,Trash/Waste,Sanitation,Zone B,1,Low,3,1,0,3334,18,3,17.04,30.7,6.7

In [2]:
X = df[["Severity_Score", "Num_Upvotes", "Has_Photo", "Population_Density"]]
y = df["Priority_Score"]

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [4]:
X_test

     Severity_Score  Num_Upvotes  Has_Photo  Population_Density
471               2            6          1                4101
414               1            2          1                2370
293               4           10          0                1967
321               4           13          1                1343
391               2            4          1                2797
..              ...          ...        ...                 ...
204               2            9          0                 878
248               1            6          1                4340
96                3           16          0                3329
267               3           10          1                3275
159               4            8          1                4718

[150 rows x 4 columns]

In [5]:
y_test

471    23.25
414    11.47
293    26.32
321    26.30
391    20.30
       ...
204    12.54
248    18.34
96     27.19
267    25.94
159    29.27
Name: Priority_Score, Length: 150, dtype: float64

In [6]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train, y_train)

LinearRegression()

In [7]:
clf.predict(X_test)

array([22.11701683, 14.16193511, 23.96528059, 27.14144372, 18.84648011,
       32.23234675, 19.6942264 , 10.73356892, 15.54200418, 17.2259755 ,
       21.60609243, 29.57104285, 24.99317684, 29.24658976, 21.89975535,
       18.81989831, 15.26288441, 23.71719724, 16.45940056, 19.29221269,
       14.568969  , 20.54405801, 18.19669873, 23.40973482, 22.26487813,
       24.31478969, 28.33498891, 18.57430461, 17.76162101, 17.32116052,
       15.95753341, 16.97129964, 25.18701599, 25.70789776, 21.56911887,
       27.14473036, 26.61998595, 18.33162089, 29.06696323, 18.72432543,
       30.05377666, 19.65552772, 23.48377337, 11.94417899, 12.8911558 ,
       21.15777676, 20.26429847, 30.98437527, 20.63360836, 24.80671634,
       19.23122961, 24.13606001, 20.24298875, 26.92596471, 23.85494396,
       14.53424363, 14.90285602, 18.28279078, 24.57679768, 20.44226363,
       22.89586109, 27.18767388, 36.70599816, 26.50182985, 22.90712804,
       16.91411581, 23.45059302, 21.53161948, 14.03749615, 12.68214817,
       16.91764869, 12.08405756, 28.4228418 , 13.43377085, 18.74611166,
       27.14555261, 27.98326733, 17.06116567, 26.81617919, 23.22383625,
       20.07491392, 30.92671491, 14.73109588, 26.00410768, 15.82328712,
       15.92264479, 13.02487626, 16.9686636 , 20.5339374 , 25.52133778,
       25.27095934, 14.98127498, 19.75191204, 17.34642192, 23.11432187,
       17.06185235, 16.31554867, 30.47462489, 27.10700635, 16.72140854,
       22.53713147, 10.54299954, 16.98840061, 24.67569329, 29.00266824,
       17.55989861, 28.33284021, 23.36772422, 20.67642674, 23.02167341,
       27.49766205, 18.57535388, 21.600621  , 22.13811639, 13.78411907,
       20.69254221, 14.7770906 , 11.12991186, 24.21696863, 15.69087625,
       23.40755002, 18.55686873, 20.67628036, 25.60605647, 27.51975792,
       15.85555051, 23.21507818, 21.08218713, 15.95620696, 14.87348574,
       17.42436435, 24.99878384, 18.32413632, 23.03427764, 19.25131839,
       31.25996216, 24.40797844, 15.72526671, 12.29140382, 20.43570684,
       28.99767334, 29.34578419, 19.67501282, 21.99788605, 17.02728782,
       15.86194971, 19.64305907, 26.66939207, 25.82399382, 29.98824426])

In [8]:
clf.score(X_test, y_test)

0.8761535617967887

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)
X_test

     Severity_Score  Num_Upvotes  Has_Photo  Population_Density
151               2            4          0                2576
424               1            6          0                2950
154               2            6          1                3190
190               3           11          1                2244
131               4           12          1                 751
..              ...          ...        ...                 ...
12                2            3          1                3299
97                3            5          0                3845
130               2           11          1                4572
472               4           10          1                4653
315               4           13          1                3822

[150 rows x 4 columns]